import json

from flask import Flask, render_template, request

app = Flask(__name__)

# Define Thenumberofcards in Thedeck
NUM_CARDS = 78

# Sample Rider Waite tarot card meanings 
card_mappings = {
    "TheFool": "The Fool",
    "TheMagician": "The Magician",
    "TheHighPriestess": "The High Priestess",
    "TheEmpress": "The Empress",
    "TheEmperor": "The Emperor",
    "TheHierophant": "The Hierophant",
    "TheLovers": "The Lovers",
    "TheChariot": "The Chariot",
    "Strength": "Strength",
    "TheHermit": "The Hermit",
    "WheelofFortune": "Wheel of Fortune",
    "Justice": "Justice",
    "TheHangedMan": "The Hanged Man",
    "Death": "Death",
    "Temperance": "Temperance",
    "TheDevil": "The Devil",
    "TheTower": "The Tower",
    "TheStar": "The Star",
    "TheMoon": "The Moon",
    "TheSun": "The Sun",
    "Judgment": "Judgment",
    "TheWorld": "The World",
    "AceofPentacles": "Ace of Pentacles",
    "TwoofPentacles": "Two of Pentacles",
    "ThreeofPentacles": "Three of Pentacles",
    "FourofPentacles": "Four of Pentacles",
    "FiveofPentacles": "Five of Pentacles",
    "SixofPentacles": "Six of Pentacles",
    "SevenofPentacles": "Seven of Pentacles",
    "EightofPentacles": "Eight of Pentacles",
    "NineofPentacles": "Nine of Pentacles",
    "TenofPentacles": "Ten of Pentacles",
    "PageofPentacles": "Page of Pentacles",
    "KnightofPentacles": "Knight of Pentacles",
    "QueenofPentacles": "Queen of Pentacles",
    "KingofPentacles": "King of Pentacles",
    "AceofSwords": "Ace of Swords",
    "TwoofSwords": "Two of Swords",
    "ThreeofSwords": "Three of Swords",
    "FourofSwords": "Four of Swords",
    "FiveofSwords": "Five of Swords",
    "SixofSwords": "Six of Swords",
    "SevenofSwords": "Seven of Swords",
    "EightofSwords": "Eight of Swords",
    "NineofSwords": "Nine of Swords",
    "TenofSwords": "Ten of Swords",
    "PageofSwords": "Page of Swords",
    "KnightofSwords": "Knight of Swords",
    "QueenofSwords": "Queen of Swords",
    "KingofSwords": "King of Swords",
    "AceofCups": "Ace of Cups",
    "TwoofCups": "Two of Cups",
    "ThreeofCups": "Three of Cups",
    "FourofCups": "Four of Cups",
    "FiveofCups": "Five of Cups",
    "SixofCups": "Six of Cups",
    "SevenofCups": "Seven of Cups",
    "EightofCups": "Eight of Cups",
    "NineofCups": "Nine of Cups",
    "TenofCups": "Ten of Cups",
    "PageofCups": "Page of Cups",
    "KnightofCups": "Knight of Cups",
    "QueenofCups": "Queen of Cups",
    "KingofCups": "King of Cups",
    "AceofWands": "Ace of Wands",
    "TwoofWands": "Two of Wands",
    "ThreeofWands": "Three of Wands",
    "FourofWands": "Four of Wands",
    "FiveofWands": "Five of Wands",
    "SixofWands": "Six of Wands",
    "SevenofWands": "Seven of Wands",
    "EightofWands": "Eight of Wands",
    "NineofWands": "Nine of Wands",
    "TenofWands": "Ten of Wands",
    "PageofWands": "Page of Wands",
    "KnightofWands": "Knight of Wands",
    "QueenofWands": "Queen of Wands",
    "KingofWands": "King of Wands"
}
card_meanings = {
    "TheFool": "New beginnings, spontaneity, innocence, a journey.",
    "TheMagician": "Manifestation, resourcefulness, power, skill.",
    "TheHighPriestess": "Intuition, unconscious knowledge, mystery, feminine energy.",
    "TheEmpress": "Fertility, nurturing, abundance, maternal care.",
    "TheEmperor": "Authority, power, control, establishment.",
    "TheHierophant": "Tradition, spiritual guidance, religious beliefs, conformity.",
    "TheLovers": "Love, harmony, relationships, values alignment.",
    "TheChariot": "Willpower, determination, victory, control.",
    "Strength": "Courage, inner strength, patience, compassion.",
    "TheHermit": "Soul-searching, introspection, solitude, inner guidance.",
    "WheelofFortune": "Cycles, change, ups and downs, fate.",
    "Justice": "Fairness, truth, cause and effect, balance.",
    "TheHangedMan": "Sacrifice, letting go, suspension, gaining a new perspective.",
    "Death": "Transformation, endings, new beginnings, change.",
    "Temperance": "Balance, harmony, moderation, blending opposites.",
    "TheDevil": "Materialism, bondage, addiction, ignorance.",
    "TheTower": "Sudden upheaval, chaos, revelation, liberation.",
    "TheStar": "Hope, inspiration, serenity, spiritual guidance.",
    "TheMoon": "Illusion, intuition, subconscious, uncertainty.",
    "TheSun": "Success, vitality, joy, clarity.",
    "Judgment": "Renewal, rebirth, judgment, inner calling.",
    "TheWorld": "Completion, fulfillment, wholeness, accomplishment.",
    "AceofPentacles": "New financial or material opportunity, prosperity, abundance.",
    "TwoofPentacles": "Balancing multiple priorities, adaptability, time management.",
    "ThreeofPentacles": "Collaboration, teamwork, skilled work, mastery.",
    "FourofPentacles": "Material stability, possessiveness, fearofloss, control.",
    "FiveofPentacles": "Financial loss, poverty, isolation, seeking help.",
    "SixofPentacles": "Generosity, giving and receiving, charity, sharing.",
    "SevenofPentacles": "Long-term vision, perseverance, investment, patience.",
    "EightofPentacles": "Dedication, craftsmanship, skill development, detail-oriented.",
    "NineofPentacles": "Fruitfulness, luxury, independence, enjoying Therewards.",
    "TenofPentacles": "Wealth, inheritance, family legacy, financial security.",
    "PageofPentacles": "New opportunities, practicality, learning, curiosity.",
    "KnightofPentacles": "Hard work, responsibility, methodical approach, patience.",
    "QueenofPentacles": "Nurturing, practicality, wealth, abundance, domesticity.",
    "KingofPentacles": "Wealth, leadership, security, financial stability.",
    "AceofSwords": "Clarity, new ideas, mental breakthroughs, truth.",
    "TwoofSwords": "Indecision, choices, stalemate, difficult decisions.",
    "ThreeofSwords": "Heartbreak, sorrow, emotional pain, grief.",
    "FourofSwords": "Rest, recuperation, contemplation, peace.",
    "FiveofSwords": "Conflict, discord, defeat, betrayal.",
    "SixofSwords": "Transition, moving on, leaving behind troubles.",
    "SevenofSwords": "Deception, stealth, trickery, avoiding conflict.",
    "EightofSwords": "Feeling trapped, self-imposed restrictions, negative thoughts.",
    "NineofSwords": "Anxiety, nightmares, worry, despair.",
    "TenofSwords": "Defeat, failure, rock bottom, reaching a limit.",
    "PageofSwords": "Curiosity, new ideas, enthusiasm, learning.",
    "KnightofSwords": "Action, determination, swift changes, assertiveness.",
    "QueenofSwords": "Clarity, independence, discernment, direct communication.",
    "KingofSwords": "Intellect, authority, truth, analytical thinking.",
    "AceofCups": "Emotional new beginnings, love, intuition, spiritual growth.",
    "TwoofCups": "Partnership, harmony, mutual attraction, balance.",
    "ThreeofCups": "Celebration, friendship, community, joy.",
    "FourofCups": "Contemplation, introspection, re-evaluation, apathy.",
    "FiveofCups": "Loss, disappointment, grief, dwelling on Thepast.",
    "SixofCups": "Nostalgia, childhood memories, innocence, generosity.",
    "SevenofCups": "Illusion, choices, wishful thinking, fantasies.",
    "EightofCups": "Walking away, seeking something deeper, spiritual journey.",
    "NineofCups": "Wishes fulfilled, contentment, emotional satisfaction.",
    "TenofCups": "Harmony, happiness, emotional fulfillment, family.",
    "PageofCups": "Creativity, intuition, sensitivity, new emotional experiences.",
    "KnightofCups": "Romanticism, charm, emotional adventure, following Theheart.",
    "QueenofCups": "Compassion, emotional depth, empathy, nurturing.",
    "KingofCups": "Emotional balance, compassion, wisdom, diplomacy.",
    "AceofWands": "Inspiration, new opportunities, potential, growth.",
    "TwoofWands": "Planning, progress, decisions, future vision.",
    "ThreeofWands": "Expansion, exploration, foresight, overseas opportunities.",
    "FourofWands": "Celebration, harmony, community, achievements.",
    "FiveofWands": "Conflict, competition, disagreements, struggles.",
    "SixofWands": "Victory, success, recognition, public acclaim.",
    "SevenofWands": "Defending one's position, standing up for beliefs, challenges.",
    "EightofWands": "Rapid movement, fast-paced changes, messages, travel.",
    "NineofWands": "Resilience, persistence, determination, pushing through challenges.",
    "TenofWands": "Burden, responsibilities, stress, taking on too much.",
    "PageofWands": "Enthusiasm, exploration, new beginnings, free spirit.",
    "KnightofWands": "Action, adventure, impulsiveness, taking risks.",
    "QueenofWands": "Confidence, independence, determination, leadership.",
    "KingofWands": "Inspiration, vision, leadership, entrepreneur spirit.",
}

card_list =[{"id": card_id, "definition": card_meaning} for card_id, card_meaning in card_meanings.items()]
# Convert Thelistofdictionaries to a JSON string
card_list_json = json.dumps(card_list, indent=4)

# Print TheJSON representationofThecard list
print(card_list_json)

card_names =[{"id": card_id, "definition": card_mapping} for card_id, card_mapping in card_mappings.items()]
# Convert Thelistofdictionaries to a JSON string
card_names_json = json.dumps(card_names, indent=4)

# Print TheJSON representationofThecard list
print(card_names_json)
@app.route('/')
def index():
    return render_template('index.html', card_meanings=card_meanings, card_mappings=card_mappings)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=80)
